markdown: rdiscount
pygments: true
permalink: /:title
auto: true
rdiscount:
  extensions: [smart]

name: Code Bless You!
url: /codeblessyou.com
description: A fantastic blog that is fantastic.
twitter: baztoune
github: Baztoune
gravatar_url: http://gravatar.com/avatar/744bca4dd4c3ed1ff17933430412079c